name: Blackpool Property Photography
favicon: null
layout_spectrum: 0.003959624795243144
typography_spectrum: 0.27883455716073513
title: Making Property Look Better Since 2015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#ffffff'
    - '#000000'
    - '#858585'
    - '#464646'
  brandStrength: 0.949362829560414
  lightness: 0.6613679509609938
  saturation: 0.3269470694940537
  rhythmicContrast: 0.5
purpose: []
