name: Blackpool Property Photography
favicon: null
layout_spectrum: 0.58211
typography_spectrum: 0.27883455716073513
title: Making Property Look Better On The Web.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#ffffff'
    - '#000000'
    - '#858585'
    - '#464646'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
